#!/usr/bin/env python3
"""Write docs/bom.md from the netlist: parts grouped by LCSC number, with live
JLCPCB stock, Basic/Extended type and unit price.

    python3 hardware/scripts/bom.py            # needs internet (public API)
"""
import os
import sys
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from netlist import NETLIST, read_netlist  # noqa: E402
from jlc import search  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "docs", "bom.md")


def refkey(r):
    head = r.rstrip("0123456789")
    return head, int(r[len(head):] or 0)


def main():
    comps, _ = read_netlist(NETLIST)
    groups, solder = OrderedDict(), OrderedDict()
    hand = []
    for ref in sorted(comps, key=refkey):
        c = comps[ref]
        code = c["fields"].get("LCSC")
        if not code:
            hand.append((ref, c))
            continue
        bucket = solder if c["fields"].get("Assembly") == "hand" else groups
        bucket.setdefault(code, {"refs": [], "value": c["value"], "fp": c["footprint"]})["refs"].append(ref)

    def table(parts):
        rows, n_ext, cost = [], 0, 0.0
        for code, g in parts.items():
            hit = next((p for p in search(code, 3) if p["componentCode"] == code), None)
            if hit:
                kind = {"base": "Basic", "expand": "Extended"}.get(hit["componentLibraryType"], "?")
                stock = hit["stockCount"]
                price = (hit.get("componentPrices") or [{}])[0].get("productPrice") or 0.0
                model = hit["componentModelEn"]
            else:
                kind, stock, price, model = "not found", 0, 0.0, "?"
            n_ext += kind == "Extended"
            cost += price * len(g["refs"])
            warn = " ⚠️" if stock < 10 * len(g["refs"]) else ""
            rows.append(f"| {', '.join(g['refs'])} | {len(g['refs'])} | {g['value']} | {model} | "
                        f"[{code}](https://jlcpcb.com/partdetail/{code}) | {kind} | {stock:,}{warn} | ${price:.4f} |")
        return rows, n_ext, cost

    head = "| Refs | Qty | Value | Part | LCSC | Type | Stock | Unit |\n|---|---|---|---|---|---|---|---|\n"
    rows, n_ext, total = table(groups)
    srows, _, stotal = table(solder)
    with open(OUT, "w") as f:
        f.write("# Bill of materials\n\n")
        f.write("Generated by `hardware/scripts/bom.py` from the netlist, with live JLCPCB stock "
                "(re-run it before ordering).\n\n")
        f.write(f"- **JLCPCB assembles {sum(len(g['refs']) for g in groups.values())} parts**: "
                f"{len(groups)} unique LCSC numbers, **{n_ext} Extended** "
                f"(JLCPCB charges a loading fee per Extended part type, about $3 each), "
                f"about **${total:.2f}** per board\n")
        f.write(f"- **You solder {sum(len(g['refs']) for g in solder.values())} parts** "
                f"(through-hole + 6x6 buttons), about **${stotal:.2f}** per board from LCSC\n\n")
        f.write("## Assembled by JLCPCB\n\n" + head + "\n".join(rows) + "\n\n")
        f.write("## You solder (order these from LCSC)\n\n"
                "Kept out of the JLCPCB BOM to skip their Extended-part fees. All are "
                "through-hole or big SMD pads.\n\n" + head + "\n".join(srows) + "\n\n")
        f.write("## Not ordered\n\n")
        for ref, c in hand:
            f.write(f"- **{ref}** {c['value']} ({c['footprint']})\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
