#!/usr/bin/env python3
"""Write docs/bom.md from the netlist: parts grouped by LCSC number, with live
JLCPCB stock, Basic/Extended type and unit price.

    python3 hardware/scripts/bom.py            # needs internet (public API)
"""
import os
import sys
from collections import OrderedDict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from netlist import NETLIST, read_netlist  # noqa: E402
from jlc import search  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "docs", "bom.md")


def refkey(r):
    head = r.rstrip("0123456789")
    return head, int(r[len(head):] or 0)


def main():
    comps, _ = read_netlist(NETLIST)
    groups = OrderedDict()
    hand = []
    for ref in sorted(comps, key=refkey):
        c = comps[ref]
        code = c["fields"].get("LCSC")
        if not code:
            hand.append((ref, c))
            continue
        groups.setdefault(code, {"refs": [], "value": c["value"], "fp": c["footprint"]})["refs"].append(ref)

    rows, n_ext, total = [], 0, 0.0
    for code, g in groups.items():
        hit = next((p for p in search(code, 3) if p["componentCode"] == code), None)
        if hit:
            kind = {"base": "Basic", "expand": "Extended"}.get(hit["componentLibraryType"], "?")
            stock = hit["stockCount"]
            price = (hit.get("componentPrices") or [{}])[0].get("productPrice") or 0.0
            model = hit["componentModelEn"]
        else:
            kind, stock, price, model = "not found", 0, 0.0, "?"
        n_ext += kind == "Extended"
        total += price * len(g["refs"])
        warn = " ⚠️" if stock < 10 * len(g["refs"]) else ""
        rows.append(f"| {', '.join(g['refs'])} | {len(g['refs'])} | {g['value']} | {model} | "
                    f"[{code}](https://jlcpcb.com/partdetail/{code}) | {kind} | {stock:,}{warn} | ${price:.4f} |")

    with open(OUT, "w") as f:
        f.write("# Bill of materials\n\n")
        f.write("Generated by `hardware/scripts/bom.py` from the netlist, with live JLCPCB stock "
                "(re-run it before ordering).\n\n")
        f.write(f"- **{sum(len(g['refs']) for g in groups.values())} assembled parts**, "
                f"{len(groups)} unique LCSC numbers, **{n_ext} Extended** "
                f"(JLCPCB charges a loading fee per Extended part type, about $3 each)\n")
        f.write(f"- Parts cost for one board: about **${total:.2f}** (1-off prices, excluding PCB and assembly fees)\n\n")
        f.write("| Refs | Qty | Value | Part | LCSC | Type | Stock | Unit |\n|---|---|---|---|---|---|---|---|\n")
        f.write("\n".join(rows) + "\n\n")
        f.write("## Not assembled by JLCPCB\n\n")
        for ref, c in hand:
            f.write(f"- **{ref}** {c['value']} ({c['footprint']})\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
